

YRI_SD_RUNTIME_VERIF="yri_sd_runtime_verif"

YRI_SD_RUNTIME_VERIF_LIB_HOME="${HOME}/${YRI_SD_RUNTIME_VERIF}"

YRI_SD_RUNTIME_VERIF_UT_HOME_DEVEL="${HOME}/yri_sd_runtime_verif_UNIT_TESTS"

YRI_SD_RUNTIME_VERIF_UT_HOME_DEVEL_UT_LIB="${YRI_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YRI_SD_RUNTIME_VERIF}"

SRC="src"

#set -x

rm -r "${YRI_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YRI_SD_RUNTIME_VERIF}"

mkdir -p "${YRI_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YRI_SD_RUNTIME_VERIF}"


cp -r ${YRI_SD_RUNTIME_VERIF_LIB_HOME}/* ${YRI_SD_RUNTIME_VERIF_UT_HOME_DEVEL_UT_LIB}


